// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package websocket

import (
	"context"
	"net"
	"ws-battleship-shared/domain"
	"ws-battleship-shared/events"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function for the type MockClient
func (_mock *MockClient) Connect(ctx context.Context, ipv4 net.IP) error {
	ret := _mock.Called(ctx, ipv4)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, net.IP) error); ok {
		r0 = returnFunc(ctx, ipv4)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockClient_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
//   - ipv4 net.IP
func (_e *MockClient_Expecter) Connect(ctx interface{}, ipv4 interface{}) *MockClient_Connect_Call {
	return &MockClient_Connect_Call{Call: _e.mock.On("Connect", ctx, ipv4)}
}

func (_c *MockClient_Connect_Call) Run(run func(ctx context.Context, ipv4 net.IP)) *MockClient_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 net.IP
		if args[1] != nil {
			arg1 = args[1].(net.IP)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_Connect_Call) Return(err error) *MockClient_Connect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Connect_Call) RunAndReturn(run func(ctx context.Context, ipv4 net.IP) error) *MockClient_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Messages provides a mock function for the type MockClient
func (_mock *MockClient) Messages() <-chan events.Event {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Messages")
	}

	var r0 <-chan events.Event
	if returnFunc, ok := ret.Get(0).(func() <-chan events.Event); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan events.Event)
		}
	}
	return r0
}

// MockClient_Messages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Messages'
type MockClient_Messages_Call struct {
	*mock.Call
}

// Messages is a helper method to define mock.On call
func (_e *MockClient_Expecter) Messages() *MockClient_Messages_Call {
	return &MockClient_Messages_Call{Call: _e.mock.On("Messages")}
}

func (_c *MockClient_Messages_Call) Run(run func()) *MockClient_Messages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Messages_Call) Return(eventCh <-chan events.Event) *MockClient_Messages_Call {
	_c.Call.Return(eventCh)
	return _c
}

func (_c *MockClient_Messages_Call) RunAndReturn(run func() <-chan events.Event) *MockClient_Messages_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function for the type MockClient
func (_mock *MockClient) Metadata() domain.ClientMetadata {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 domain.ClientMetadata
	if returnFunc, ok := ret.Get(0).(func() domain.ClientMetadata); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(domain.ClientMetadata)
	}
	return r0
}

// MockClient_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockClient_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockClient_Expecter) Metadata() *MockClient_Metadata_Call {
	return &MockClient_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockClient_Metadata_Call) Run(run func()) *MockClient_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Metadata_Call) Return(clientMetadata domain.ClientMetadata) *MockClient_Metadata_Call {
	_c.Call.Return(clientMetadata)
	return _c
}

func (_c *MockClient_Metadata_Call) RunAndReturn(run func() domain.ClientMetadata) *MockClient_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type MockClient
func (_mock *MockClient) SendMessage(e events.Event) error {
	ret := _mock.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(events.Event) error); ok {
		r0 = returnFunc(e)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockClient_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - e events.Event
func (_e *MockClient_Expecter) SendMessage(e interface{}) *MockClient_SendMessage_Call {
	return &MockClient_SendMessage_Call{Call: _e.mock.On("SendMessage", e)}
}

func (_c *MockClient_SendMessage_Call) Run(run func(e events.Event)) *MockClient_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 events.Event
		if args[0] != nil {
			arg0 = args[0].(events.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_SendMessage_Call) Return(err error) *MockClient_SendMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_SendMessage_Call) RunAndReturn(run func(e events.Event) error) *MockClient_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockClient
func (_mock *MockClient) Shutdown() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockClient_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockClient_Expecter) Shutdown() *MockClient_Shutdown_Call {
	return &MockClient_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockClient_Shutdown_Call) Run(run func()) *MockClient_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Shutdown_Call) Return(err error) *MockClient_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Shutdown_Call) RunAndReturn(run func() error) *MockClient_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}
