// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"
	"ws-battleship-shared/events"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClient
func (_mock *MockClient) Close() {
	_mock.Called()
	return
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return() *MockClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func()) *MockClient_Close_Call {
	_c.Run(run)
	return _c
}

// ID provides a mock function for the type MockClient
func (_mock *MockClient) ID() ClientID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 ClientID
	if returnFunc, ok := ret.Get(0).(func() ClientID); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(ClientID)
	}
	return r0
}

// MockClient_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockClient_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockClient_Expecter) ID() *MockClient_ID_Call {
	return &MockClient_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockClient_ID_Call) Run(run func()) *MockClient_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_ID_Call) Return(v ClientID) *MockClient_ID_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockClient_ID_Call) RunAndReturn(run func() ClientID) *MockClient_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockClient
func (_mock *MockClient) Ping() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *MockClient_Expecter) Ping() *MockClient_Ping_Call {
	return &MockClient_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *MockClient_Ping_Call) Run(run func()) *MockClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Ping_Call) Return(err error) *MockClient_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Ping_Call) RunAndReturn(run func() error) *MockClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// ReadMessages provides a mock function for the type MockClient
func (_mock *MockClient) ReadMessages(ctx context.Context, messagesCh chan<- events.Event) {
	_mock.Called(ctx, messagesCh)
	return
}

// MockClient_ReadMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadMessages'
type MockClient_ReadMessages_Call struct {
	*mock.Call
}

// ReadMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - messagesCh chan<- events.Event
func (_e *MockClient_Expecter) ReadMessages(ctx interface{}, messagesCh interface{}) *MockClient_ReadMessages_Call {
	return &MockClient_ReadMessages_Call{Call: _e.mock.On("ReadMessages", ctx, messagesCh)}
}

func (_c *MockClient_ReadMessages_Call) Run(run func(ctx context.Context, messagesCh chan<- events.Event)) *MockClient_ReadMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chan<- events.Event
		if args[1] != nil {
			arg1 = args[1].(chan<- events.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ReadMessages_Call) Return() *MockClient_ReadMessages_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_ReadMessages_Call) RunAndReturn(run func(ctx context.Context, messagesCh chan<- events.Event)) *MockClient_ReadMessages_Call {
	_c.Run(run)
	return _c
}

// SendMessage provides a mock function for the type MockClient
func (_mock *MockClient) SendMessage(eventType events.EventType, obj any) error {
	ret := _mock.Called(eventType, obj)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(events.EventType, any) error); ok {
		r0 = returnFunc(eventType, obj)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockClient_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - eventType events.EventType
//   - obj any
func (_e *MockClient_Expecter) SendMessage(eventType interface{}, obj interface{}) *MockClient_SendMessage_Call {
	return &MockClient_SendMessage_Call{Call: _e.mock.On("SendMessage", eventType, obj)}
}

func (_c *MockClient_SendMessage_Call) Run(run func(eventType events.EventType, obj any)) *MockClient_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 events.EventType
		if args[0] != nil {
			arg0 = args[0].(events.EventType)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_SendMessage_Call) Return(err error) *MockClient_SendMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_SendMessage_Call) RunAndReturn(run func(eventType events.EventType, obj any) error) *MockClient_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// WriteMessages provides a mock function for the type MockClient
func (_mock *MockClient) WriteMessages(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockClient_WriteMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteMessages'
type MockClient_WriteMessages_Call struct {
	*mock.Call
}

// WriteMessages is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) WriteMessages(ctx interface{}) *MockClient_WriteMessages_Call {
	return &MockClient_WriteMessages_Call{Call: _e.mock.On("WriteMessages", ctx)}
}

func (_c *MockClient_WriteMessages_Call) Run(run func(ctx context.Context)) *MockClient_WriteMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_WriteMessages_Call) Return() *MockClient_WriteMessages_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_WriteMessages_Call) RunAndReturn(run func(ctx context.Context)) *MockClient_WriteMessages_Call {
	_c.Run(run)
	return _c
}
